version: "3.9"

services: 
  
  # app:
  #   image: node:12-alpine
  #   command: sh -c "npm install && npm run dev"
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_DB: todos

  mysql:
    image: mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: todos 
    ports:
      - 3307:3306
  
  app:
    build: . 
    command: npm start
    container_name: smartfit
    ports:
      - 3000:3000
    volumes:
      - .:/app

volumes:
  todo-mysql-data:
