version: "3.9"

services: 
  mysql:
    image: mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  
  app:
    build: . 
    command: npm start
    container_name: smartfit
    ports:
      - 3000:3000
    volumes:
      - .:/app

volumes:
  todo-mysql-data: