version: "3.9"

services: 
  mysql:
    image: mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  
  app:
    build: . 
    # command: npm start
    container_name: smartfit
    restart: always 
    command: sh -c "sleep 30s && npx prisma migrate dev --name db-smart-api && node ./prisma/seed/seed.js && npm start"
    depends_on: 
            - mysql
    ports:
      - 3000:3000
    volumes:
      - .:/app

volumes:
  todo-mysql-data: